### ISSUE TITLE
Mehrere Stylesheets

### ISSUE THREAD

**Issue by danspringer** [eaCe/module_styles#1]
Es wäre toll, wenn man in den Einstellungen mehrere Stylesheets zeilenbasiert eingeben könnte.
Ich habe zB diverse Seiten, bei denen die Styles aufgeteilt sind und nicht alle in einer File eingebunden werden.

**Comment by eaCe** [comment]
Ist erledigt

**Comment by danspringer** [comment]
Du bist ja der wahnsinn! :-) <3
